### ISSUE TITLE
Touchpad scrolling doesn't work

### ISSUE THREAD

**Issue by vadz** [LibVNC/macVNC#5]
I'm using a touchpad (under Wayland, if it matters) on the client side and scrolling using 2-finger gestures works just fine, but it doesn't do anything when using macvnc, neither with gvncviewer nor with remmina. I'm not really sure who is responsible for translating mouse gestures like this to the events, but this is a rather big usability problem as I can't bring up the "invisible by default" (thanks Apple) scrollbars neither, so I basically can't scroll anything on the remote machine, so it would be great to have some workaround.

**Comment by bk138** [comment]
Got a traditional "works for me here" case :roll_eyes:  (macOS 14 Sonoma) Would you be comfortable to to add some printf's to the cases in https://github.com/LibVNC/macVNC/blob/b00f23f33e5f61d0a975278bb25246da711067c5/src/mac.c#L401 and see what gets reported?

**Comment by vadz** [comment]
I'm awfully sorry, I got confused and tested this only with gvncviewer ("Remove Viewer" in GNOME) which seems to not send any scroll events at all. This does work correctly with remmina (confirmed after adding debugging `printf()`s...).

The other bug, with cursor leaving traces still happens with both clients, however.
