### ISSUE TITLE
Display artefacts when showing text cursor in the Terminal window

### ISSUE THREAD

**Issue by vadz** [LibVNC/macVNC#6]
I've realized that the display artefacts I was seeing were due to showing the I-shaped cursor in addition to the normal mouse cursor when the mouse is in the Terminal window and this I-cursor leaves traces when moving the mouse around, see

![image](https://github.com/LibVNC/macVNC/assets/146917/d31a4877-d2fe-4912-9bdb-6abf8fcbb554)

where I just wiggled the mouse in a terminal window.

Note that I also the mouse arrow cursor on the screen but GNOME screenshot doesn't allow me to capture it.

Also, this happens with both gvncviewer and remmina (but they seem to use the same underlying library anyhow).

**Comment by bk138** [comment]
Can't repro on my Intel Mac :-/. Do you happen to use an M1/M2?

**Comment by vadz** [comment]
Yes, this is an M1 Mac mini.

Out of curiosity, do you see 2 cursors as well in the Terminal?

**Comment by bk138** [comment]
OK, I'll try on an M1. For reference, here's what it looks like for me from Debian Remmina -> MacOS 14. The text selector cursor is the one on the server, the arrow the client side pointer.

[Bildschirmaufzeichnung vom 2024-03-08, 20-59-12.webm](https://github.com/LibVNC/macVNC/assets/80450/9db61698-840d-412e-9521-206bea35966a)

**Comment by bk138** [comment]
@vadz please check with 2b05b6ccad6c346410c718adbd7bad73a8062832 if you happen to find the time. This should not happen anymore as we now have to send the whole screen always, not just the changed rects.

**Comment by bk138** [comment]
Closing, should be fixed.
