### ISSUE TITLE
[Question] Is there a configuration file or directory for macVNC?

### ISSUE THREAD

**Issue by sarkrui** [LibVNC/macVNC#8]
Hi, 

I ran macVNC on port 5901 and tried to connect on another Mac with Screen Sharing via ip:5901. It prompted a password enter box. I've tried using the password for the user running the macVNC. Didn't seem to work, showing "Connecting..." 

On the server side, there is no salient error shown. 
<img width="882" alt="image" src="https://github.com/LibVNC/macVNC/assets/14228455/36ca4ad1-c260-4424-8252-154fe86af6ea">

Meanwhile, there was an error with bind with IPv6 address. Thanks.

**Comment by bk138** [comment]
Might be that the viewer tries to connect via IPv6. You can try with `./macvnc -rfbport 5901 -rfbportv6 5901` to have it listen on IPv4 and IPv6 port 5901.
