### ISSUE TITLE
m1-m3 mac code signing issues 

### ISSUE THREAD

**Issue by hotelzululima** [LibVNC/macVNC#9]
Unfortunately running on an M3pro Macbook pro elicits
unsure about how to resolve as I dont have a mac developer cert..

 

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

much crap deleted 

but I did csrutil disable the system in question, added iterm(what I use) to screen recording and all seems to be coming up now.  So adhoc(linker) signing does NOT seem working on this pass of ventura 14.5 on m3pro

**Comment by hotelzululima** [comment]
issue is described here.. https://github.com/Homebrew/brew/issues/9082

**Comment by hotelzululima** [comment]
ok I was able to create a local ca & codesigning cert(https://www.simplified.guide/macos/keychain-cert-code-signing-create)  and have a command line util for installing the caname.cer file on client machine under my control (sudo  security add-certificates -k /Library/Keychains/System.keychain caname.cer)
the readme in the root dir needed to be removed as it prevented successful codesigning(https://stackoverflow.com/questions/25950544/codesign-what-are-unsealed-contents).    that solves the codesigning issues for moi so I am closing this

**Comment by WestonThayer** [comment]
Adding onto this for others who may need help. No error is visible when running `./macVNC.app/Contents/MacOS/macVNC` from terminal, it just says killed. But if you double click the `.app` and choose the Report option, the message contains `EXC_BAD_ACCESS (SIGKILL (Code Signature Invalid))`.

You can simply fix this via:

```sh
# Remove the README, as noted above
rm ./macVNC.app/README.md
# Apply an ad-hoc signature. codesign should be installed if you have Homebrew
codesign --force --deep --sign - ./macVNC.app
```

Now it should launch.
